import test from 'node:test'
import assert from 'node:assert/strict'
import request from 'supertest'
process.env.NODE_ENV = 'test'
const { app } = await import('./index.js')

test('health and seeded systems', async () => { assert.equal((await request(app).get('/api/health')).status, 200); const response = await request(app).get('/api/ai-systems'); assert.equal(response.status, 200); assert.ok(response.body.data.length >= 5) })
test('create and validate inventory', async () => { const created = await request(app).post('/api/ai-systems').send({ name: `QA ${Date.now()}`, owner: 'QA Team', risk: 'Low', status: 'Pilot' }); assert.equal(created.status, 201); assert.equal((await request(app).get(`/api/ai-systems/${created.body.data.id}`)).status, 200); assert.equal((await request(app).post('/api/ai-systems').send({ name: '' })).status, 422) })
test('risk, vetting, escalation, roadmap workflows', async () => { assert.equal((await request(app).post('/api/risk-assessments').send({ name: 'QA model', category: 'Privacy', score: 4, owner: 'QA' })).status, 201); const vet = await request(app).post('/api/vetting-requests').send({ name: 'QA vendor', type: 'External vendor', submitted: 'QA' }); assert.equal((await request(app).put(`/api/vetting-requests/${vet.body.data.id}`).send({ decision: 'Approved' })).body.data.decision, 'Approved'); const escalation = await request(app).post('/api/escalations').send({ system: 'QA', summary: 'Test escalation', severity: 'Low', owner: 'QA' }); assert.equal((await request(app).put(`/api/escalations/${escalation.body.data.id}`).send({ status: 'Resolved', resolution: 'Done' })).body.data.status, 'Resolved'); const roadmap = await request(app).get('/api/roadmap'); assert.equal((await request(app).put(`/api/roadmap/milestones/${roadmap.body.data[1].items[0].id}`).send({ completed: true })).status, 200) })
test('roadmap returns persisted progress and rejects missing milestones', async () => { const roadmap = await request(app).get('/api/roadmap'); assert.equal(roadmap.status, 200); assert.equal(roadmap.body.progress.total, 12); const milestone = roadmap.body.data[0].items[0]; const original = milestone.completed; const updated = await request(app).put(`/api/roadmap/milestones/${milestone.id}`).send({ completed: !original }); assert.equal(updated.status, 200); const refreshed = await request(app).get('/api/roadmap'); assert.equal(refreshed.body.progress.completed, roadmap.body.progress.completed + (original ? -1 : 1)); const restored = await request(app).put(`/api/roadmap/milestones/${milestone.id}`).send({ completed: original }); assert.equal(restored.status, 200); assert.equal((await request(app).put('/api/roadmap/milestones/999999').send({ completed: true })).status, 404) })
